apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
data:
  {{- range $i, $instance := .Values.instances }}
  {{ include "rust.fullname" $ }}-{{ $i }}: |
    {{- range $key, $value := $instance }}
    {{- if not (has $key (list "rconPassword" "existingSecret" "service")) }}
    {{ $key }}={{ $value }}
    {{- end }}
    {{- end }}
  {{- end }}