apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
data:
  {{- range $i, $instance := .Values.instances }}
  {{ include "rust.fullname" . }}-{{ $i }}: |
    {{- toYaml $instance | nindent 4}}
  {{- end }}