apiVersion: v1
kind: Service
metadata:
  name: {{ include "rust.fullname" . }}
  labels:
    {{- include "rust.labels" . | nindent 4 }}
  {{- with .Values.headlessService.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.headlessService.type }}
  clusterIP: None
  ports:
    - name: server-port
      port: {{ .Values.rustDedicatedServer.serverPort }}
      targetPort: server-port
      protocol: UDP
    - name: rcon-port
      port: {{ .Values.rustDedicatedServer.rconPort }}
      targetPort: rcon-port
      protocol: TCP
    - name: query-port
      port: {{ .Values.rustDedicatedServer.serverQueryPort }}
      targetPort: query-port
      protocol: UDP
    - name: app-port
      port: {{ .Values.rustDedicatedServer.appPort }}
      targetPort: app-port
      protocol: TCP
  selector:
    {{- include "rust.selectorLabels" . | nindent 4 }}
