{{- range $i, $instance := .Values.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rust.fullname" $ }}-{{ $i }}
  labels:
    {{- include "rust.labels" $ | nindent 4 }}
  {{- with $instance.service.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $instance.service.type }}
  externalTrafficPolicy: {{ $instance.service.externalTrafficPolicy }}
  ports:
    - name: server-port
      port: {{ $.Values.rustDedicatedServer.serverPort }}
      targetPort: server-port
      protocol: UDP
    - name: rcon-port
      port: {{ $.Values.rustDedicatedServer.rconPort }}
      targetPort: rcon-port
      protocol: TCP
    - name: query-port
      port: {{ $.Values.rustDedicatedServer.serverQueryPort }}
      targetPort: query-port
      protocol: UDP
    - name: app-port
      port: {{ $.Values.rustDedicatedServer.appPort }}
      targetPort: app-port
      protocol: TCP
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "rust.fullname" $ }}-{{ $i }}
{{- end }}